export const COUNTRY_CODES_BY_CONTINENT = {
  Asia: [
    { iso: "IN", name: "India", dialCode: "+91" },
    { iso: "CN", name: "China", dialCode: "+86" },
    { iso: "JP", name: "Japan", dialCode: "+81" },
    { iso: "KR", name: "South Korea", dialCode: "+82" },
    { iso: "SG", name: "Singapore", dialCode: "+65" },
    { iso: "MY", name: "Malaysia", dialCode: "+60" },
    { iso: "TH", name: "Thailand", dialCode: "+66" },
    { iso: "VN", name: "Vietnam", dialCode: "+84" },
    { iso: "PH", name: "Philippines", dialCode: "+63" },
    { iso: "ID", name: "Indonesia", dialCode: "+62" },
    { iso: "PK", name: "Pakistan", dialCode: "+92" },
    { iso: "BD", name: "Bangladesh", dialCode: "+880" },
    { iso: "LK", name: "Sri Lanka", dialCode: "+94" },
    { iso: "NP", name: "Nepal", dialCode: "+977" },
    { iso: "AE", name: "United Arab Emirates", dialCode: "+971" },
    { iso: "SA", name: "Saudi Arabia", dialCode: "+966" },
    { iso: "QA", name: "Qatar", dialCode: "+974" },
    { iso: "KW", name: "Kuwait", dialCode: "+965" },
    { iso: "IL", name: "Israel", dialCode: "+972" },
    { iso: "TR", name: "Turkey", dialCode: "+90" },
  ],

  Europe: [
    { iso: "GB", name: "United Kingdom", dialCode: "+44" },
    { iso: "FR", name: "France", dialCode: "+33" },
    { iso: "DE", name: "Germany", dialCode: "+49" },
    { iso: "IT", name: "Italy", dialCode: "+39" },
    { iso: "ES", name: "Spain", dialCode: "+34" },
    { iso: "NL", name: "Netherlands", dialCode: "+31" },
    { iso: "BE", name: "Belgium", dialCode: "+32" },
    { iso: "CH", name: "Switzerland", dialCode: "+41" },
    { iso: "SE", name: "Sweden", dialCode: "+46" },
    { iso: "NO", name: "Norway", dialCode: "+47" },
    { iso: "FI", name: "Finland", dialCode: "+358" },
    { iso: "DK", name: "Denmark", dialCode: "+45" },
    { iso: "IE", name: "Ireland", dialCode: "+353" },
    { iso: "PL", name: "Poland", dialCode: "+48" },
    { iso: "RO", name: "Romania", dialCode: "+40" },
    { iso: "UA", name: "Ukraine", dialCode: "+380" },
    { iso: "RU", name: "Russia", dialCode: "+7" },
    { iso: "GR", name: "Greece", dialCode: "+30" },
  ],

  Africa: [
    { iso: "ZA", name: "South Africa", dialCode: "+27" },
    { iso: "NG", name: "Nigeria", dialCode: "+234" },
    { iso: "KE", name: "Kenya", dialCode: "+254" },
    { iso: "EG", name: "Egypt", dialCode: "+20" },
    { iso: "GH", name: "Ghana", dialCode: "+233" },
    { iso: "ET", name: "Ethiopia", dialCode: "+251" },
    { iso: "DZ", name: "Algeria", dialCode: "+213" },
    { iso: "MA", name: "Morocco", dialCode: "+212" },
    { iso: "TN", name: "Tunisia", dialCode: "+216" },
  ],

  NorthAmerica: [
    { iso: "US", name: "United States", dialCode: "+1" },
    { iso: "CA", name: "Canada", dialCode: "+1" },
    { iso: "MX", name: "Mexico", dialCode: "+52" },
    { iso: "CU", name: "Cuba", dialCode: "+53" },
    { iso: "DO", name: "Dominican Republic", dialCode: "+1" },
  ],

  SouthAmerica: [
    { iso: "BR", name: "Brazil", dialCode: "+55" },
    { iso: "AR", name: "Argentina", dialCode: "+54" },
    { iso: "CL", name: "Chile", dialCode: "+56" },
    { iso: "CO", name: "Colombia", dialCode: "+57" },
    { iso: "PE", name: "Peru", dialCode: "+51" },
    { iso: "BO", name: "Bolivia", dialCode: "+591" },
    { iso: "UY", name: "Uruguay", dialCode: "+598" },
  ],

  Oceania: [
    { iso: "AU", name: "Australia", dialCode: "+61" },
    { iso: "NZ", name: "New Zealand", dialCode: "+64" },
    { iso: "PG", name: "Papua New Guinea", dialCode: "+675" },
    { iso: "FJ", name: "Fiji", dialCode: "+679" },
  ],
};
